####  signup admin
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name":"adm1i1n",
    "email":"dson49822@gmail.com",
    "password":"12334144"
    
}

####  signup user
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name":"user133112",
    "email":"user112331",
    "password":"3"
    
}



########login admin
POST http://localhost:3000/signin
Content-Type: application/json

{
    "name":"adm1i1n",
    "email":"dson49822@gmail.com",
    "password":"12334144"
    
}


########login user
POST http://localhost:3000/signin
Content-Type: application/json

{
    "name":"user133112",
    "email":"user112331",
    "password":"3"
    
}